# This config is meant for local development only

[WebAPI]
  adminbind = "localhost"  # avoids macOS firewall confirmation!
  adminport = "8081"
  # adminbearertoken = "your-secret-token"  # Optional: when set, requires this token for admin API access
  pubbind = "localhost"  # avoids macOS firewall confirmation!
  pubport = "8082"
  # pubbearertoken = "your-secret-token"  # Optional: when set, requires this token for public API access  
  pubapirooturl = "http://localhost:8082"

[Store]
#  SQLite: (default)
#  DBFile = "gigawallet.db"
#  Postgres:
#  DBFile = "postgres://username:password@localhost/gigawallet?sslmode=disable"

[gigawallet]
  network = "mainnet"  # which dogecoind to connect to

[dogecoind.testnet]
  host    = "localhost"
  zmqport = 28332
  rpcport = 44555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

[dogecoind.mainnet]
  host    = "127.0.0.1"
  zmqport = 28332
  rpchost = "127.0.0.1"
  rpcport = 22555
  rpcpass = "gigawallet"
  rpcuser = "gigawallet"

## Setup loggers, see pkg/config.go LoggersConfig
[loggers.events]
  path = "./events.log"
  types = ["ALL"]

## Setup http Callbacks, see pkg/config.go CallbackConfig

#[callbacks.example1]
#  path = "https://example.com/invoiceEvents"
#  types = ["INV"]
#  # Optional: Add HMAC secret for request signing
#  # hmacsecret = "your-secret-key-here"


## Setup MQTT event publishing, see pkg/config.go MQTTConfig

#[mqtt]
#  address = "test.mosquitto.org:1884"
#  username = "rw"
#  password = "readwrite"
#  clientid = "gigawallet"
#
#[mqtt.queues.accounts]
#  topicfilter = "account"
#  Types = ["ACC"]
